prog : main.o fonction.o option.o intro.o quitter.o gfxutils.o integration.o scrolling.o ennemi.o perso.o autre.o Karim_Akkari_1A30.o enigmeSlim.o
	gcc -o prog main.o fonction.o option.o intro.o quitter.o gfxutils.o integration.o scrolling.o ennemi.o perso.o autre.o Karim_Akkari_1A30.o enigmeSlim.o -lm -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf -g
main.o : main.c
	gcc -o main.o -c main.c -lm -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf -g
fonction.o : fonction.c
	gcc -o fonction.o -c fonction.c -lm -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf -g
option.o : option.c
	gcc -o option.o -c option.c -lm -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf -g
intro.o : intro.c
	gcc -o intro.o -c intro.c -lm -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf -g
quitter.o : quitter.c
	gcc -o quitter.o -c quitter.c -lm -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf -g
gfxutils.o : gfxutils.c
	gcc -o gfxutils.o -c gfxutils.c -lm -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf -g
integration.o : integration.c
	gcc -o integration.o -c integration.c -lm -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf -g
scrolling.o : scrolling.c
	gcc -o scrolling.o -c scrolling.c -lm -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf -g
ennemi.o : ennemi.c
	gcc -o ennemi.o -c ennemi.c -lm -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf -g
perso.o : perso.c
	gcc -o perso.o -c perso.c -lm -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf -g
autre.o : autre.c
	gcc -o autre.o -c autre.c -lm -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf -g
Karim_Akkari_1A30.o : Karim_Akkari_1A30.c
	gcc -o Karim_Akkari_1A30.o -c Karim_Akkari_1A30.c -lm -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf -g
enigmeSlim.o : enigmeSlim.c
	gcc -o enigmeSlim.o -c enigmeSlim.c -lm -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf -g



